# Generated by Django 5.1.7 on 2025-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("muscle_group", models.CharField(max_length=50)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Principiante", "Principiante"),
                            ("Intermedio", "Intermedio"),
                            ("Avanzado", "Avanzado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="exercises/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
