# Generated by Django 5.1.7 on 2025-03-31 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="image",
        ),
    ]
