# Generated by Django 5.1.7 on 2025-04-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_remove_exercise_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
